# Generated by Django 3.2.7 on 2021-09-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('issued_to', models.CharField(max_length=120)),
                ('issued_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
